- prediction.go
- replicate_test.go
A prediction has `created_at`, `started_at`, and `completed_at` timestamps, but no `updated_at` field.
See https://replicate.com/docs/reference/http
> Remove nonexistent property `UpdatedAt` in `Prediction`

- prediction.go
- replicate_test.go
Replicate's API provides a [`urls` field](https://replicate.com/docs/reference/http#predictions.get) in responses for predictions and trainings. This PR adds this property to the corresponding models.
> Add `URLs` field to `Prediction` and `Training` types

- client.go
- prediction.go
- replicate_test.go
- run.go
- wait.go
Related to #6 
This PR updates the `Wait` function to use functional options instead of positional arguments. It also adds a `WaitAsync` variation that uses channels.
> Update `Wait` to use functional options and add async variation

- apierror.go
- backoff.go
- client.go
- replicate_test.go
- run.go
- wait.go
This PR introduces behavior to automatically retry them as appropriate (429 status code, as well as 5xx errors for GET requests). If the server sends a `Retry-After` header, that value is used. Otherwise, the function delays for the duration specified by the configured backoff strategy.
This should all be in line with the [retry logic in the Python client](https://github.com/replicate/replicate-python/blob/52f88eb3349c92c33608549ef992792172f951ed/replicate/client.py#L17-L63).
> Add automatic retry policy

- collection.go
- model.go
- paginate.go
- prediction.go
For the [CLI](https://github.com/replicate/cli), it'd be helpful to print the original JSON sent from the server. Currently, the Go objects are decoded from the server JSON and re-encoded into JSON, which would omit any fields that aren't accounted for in the model.
This PR adds an internal `rawJSON` field to structs, which stores the raw JSON message passed in `UnmarshalJSON`. If `rawJSON` isn't blank, `MarshalJSON` returns this value directly; otherwise, the object is marshaled normally.
> Store and retrieve raw JSON response from server

- model.go
- replicate_test.go
See https://replicate.com/docs/reference/http#models.list
> Add support for `models.list` endpoint

- hardware.go
- model.go
- replicate_test.go
See https://replicate.com/docs/reference/http#models.create
> Add support for `models.create` and `hardware.list` endpoints

- client_test.go
- prediction.go
- training.go
This endpoint is missing for Go client although JS and Python SDK supports it.
> Add support for `/predictions/{id}/cancel` endpoint

- client_test.go
- prediction.go
> Add fields for other prediction metrics

- client_test.go
- model.go
This PR adds support for deleting a model version.
If I'm not mistaken, HTTP endpoint is currently not supported by either JS or Python client libraries.
It might be worth considering adding support for other client libraries as well.
> Add support for `DELETE /models/{modelOwner}/{modelName}/versions/{versionID}` endpoint

- account.go
- collection.go
- deployment.go
- files.go
- hardware.go
- model.go
- paginate.go
- prediction.go
- webhook.go
#19 updated resources to store raw JSON content when unmarshaling from API responses. This allowed applications like the CLI, for example, to show any new fields that were added to the API but not yet reflected in the Go client library.
However, this can create some unexpected results if you attempt to re-encode a resource after making any changes. The current implementation of `MarshalJSON` would have any `rawJSON` value returned, if present, with no mechanism for invalidating or resetting state of any of the fields were modified.
This PR removes those `MarshalJSON` functions in favor of using the built-in marshaling based on the structures. To access the original JSON from the API response, you can now use the `RawJSON` method.
> Replace custom `MarshalJSON` implementations with `RawJSON` instance method

- client.go
Replicate's API now supports the standard [Bearer authentication scheme](https://swagger.io/docs/specification/authentication/bearer-authentication/). 
https://replicate.com/changelog/2024-04-03-bearer-tokens
For compatibility with existing clients, the existing `Token` scheme will be supported indefinitely. But going forward, the new `Bearer` scheme is preferred.
> Use Bearer authorization scheme

- README.md
This PR updates the README with some docs about webhooks and how to use the client's built in `replicate.ValidateWebhookRequest` method.
> document webhook validation

- client_test.go
- webhook.go
Hi!
I couldn't find any contribution guidelines in the repository, so I've done my best to follow the existing conventions. If there are any issues with this contribution, please let me know.
To give a bit of context on the change: I started using the `ValidateWebhookRequest` function in the API I was developing. However, I encountered an issue where the HTTP request body was left empty after validation and I needed it for further processing. While I implemented a workaround on my end, I believe the proper solution is to reset the buffer inside the validation function to avoid interfering with any of the input data. More people might encounter this issue when the library is more widely used, so I thought I would attempt to make this change directly in the library. I look forward to your …
> Reset HTTP request body after reading the stream during webhook validation

- Makefile
- client_test.go
- model.go
This PR adds support for the deleting an "empty" model.
Removes the need to navigate to the dashboard to manually delete a empty model!
Along the way, 33c6d1a673733951393dd3860d389ccd64f53ece removes an empty line.
> Add support for `DELETE /models/{modelOwner}/{modelName}`

- client_test.go
- example_test.go
- model.go
See https://replicate.com/docs/reference/http#models.search
> Add support for `models.search` endpoint

- client_test.go
- run.go
This PR introduces a new `WithFileOutput()` option for a new `RunWithOptions` method in the Go client SDK. This option abstracts away file outputs from Replicate models, making it easier to work with file outputs and allowing for future optimizations in file asset delivery.
The new option can be used as follows:
```go
output, err := client.RunWithOptions(ctx, "black-forest-labs/flux-schnell", input, nil, WithFileOutput())
reader, ok := output.(io.ReadCloser)
if ok {
defer reader.Close()
// Read from the reader
data, err := io.ReadAll(reader)
// Or stream the data
_, err := io.Copy(destinationWriter, reader)
}
```
> Add RunWithOptions method that supports returning file output as `io.ReadCloser`

- stream.go
This PR makes the following improvements to our streaming code:
* Ensures `resp.Body` always closes
* Improve context cancellation handling
* Add non-blocking send to `lineChan` and `errChan`
> Improve error handling and resource management in `streamPrediction`

- stream.go
> Fix server sent event decoding

- run.go
Follow-up to #82 
This PR brings the Go client in line with the JS client behavior updated by https://github.com/replicate/replicate-javascript/pull/315. Specifically, this updates the code for `RunWithOptions` to not poll if the `WithBlockUntilDone` option is passed and the prediction status isn't `"starting"`.
> Fix behavior of `RunWithOptions` when wait is set

- Makefile
This is raising false positives.  http.Client#Do guarantees that the response is non-nil if err is nil.
See uber/nilaway#126.
> remove nilaway

- README.md
- client_test.go
- run.go
hye, It wasn't possible to call just "black-forest-labs/flux-schnell" model, official model wihtout version... now it is !
> Update `Run` method to support versionless models
